title: キハヌジ語 学習サイト
description: |-
  <a href="walkthrough">初級編</a><br>
  <a href="dictionary">単語帳</a><br>
  <a href="reference">リンク集</a>
theme: jekyll-theme-minimal
github:
  is_project_page: false
  is_user_page: false
