title: キハヌジ語を学ぼう
#url: https://tily.github.io
#path: /kihwanujish/
#baseurl: https://tily.github.io/kihwanujish/
description: |-
  > <a href="/kihwanujish/walkthrough">初級編</a><br>
  > <a href="/kihwanujish/dictionary">単語帳</a><br>
  > <a href="/kihwanujish/reference">リンク集</a>
  > <a href="/kihwanujish/manga">マンガで分かるキハヌジ語</a>
logo: /assets/images/ogmo.jpg
theme: jekyll-theme-minimal
github:
  is_project_page: false
  is_user_page: false
