title: キハヌジ語 学習
url: https://tily.github.io
path: /kihwanujish/
description: |-
  > <a href="walkthrough">初級編</a><br>
  > <a href="dictionary">単語帳</a><br>
  > <a href="reference">リンク集</a>
logo: /assets/images/ogmo.jpg
theme: jekyll-theme-minimal
github:
  is_project_page: false
  is_user_page: false
